language: node_js
os:
  - windows
  - linux
node_js:
  - 11
  - 10
  - 8
env:
  - FRESH_DEPS=true
matrix:
  include:
    # Only verify package-lock.json on node.js 11 for linux
    - node_js: 11
      env: FRESH_DEPS=false
      os: linux
script: npm run coverage
cache: npm
install: npm ci
before_script: |
  if [[ ${FRESH_DEPS} == "true" ]]; then
    npm install --no-shrinkwrap --prefer-online
  else
    checksum=$(md5sum package-lock.json)
    npm install --package-lock-only
    if ! echo ${checksum} | md5sum --quiet -c -; then
      echo "package-lock.json was modified unexpectedly. Please rebuild it using npm@$(npm -v) and commit the changes."
      exit 1
    fi
  fi

  if [[ "${TRAVIS_OS_NAME}" == 'windows' ]]; then
    git config core.symlinks true
    git reset --hard
  fi
after_success: npx codecov --file=./coverage/lcov.info
