language: node_js
node_js:
  - "4"
  - "6"
  - "7"
script: npm test
notifications:
  email: false
script: npm run coverage
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
