build: off
cache:
  - '%APPDATA%\npm-cache'
clone_depth: 1
skip_branch_with_pr: true
skip_commits:
  files:
    - '**/*.md'
configuration:
  - FreshDeps
  - LockedDeps
environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 8
    - nodejs_version: 6
matrix:
  fast_finish: true
  exclude:
    - configuration: FreshDeps
      nodejs_version: 6
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@^5.3.0
  - npm --version
  - ps: if ($env:configuration -eq "FreshDeps") { Remove-Item package-lock.json }
  - if %configuration% == FreshDeps (npm install --prefer-online)
  - if %configuration% == LockedDeps (npm install --prefer-online)
test_script:
  - npm test
